name: CI

on:
  pull_request:
  push:

env:
  CODESPACES: "true"

jobs:

  lint:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Lint install.sh
        run: shellcheck ./install.sh

  run:
    name: Run install.sh
    strategy:
      matrix:
        preinstall_omz: ["", "true"]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y zsh
      - name: Install OMZ
        if: matrix.preinstall_omz
        run: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" --unattended
      - name: Run install.sh
        run: ./install.sh
