name: CI

on:
  pull_request:
  push:

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    container: koalaman/shellcheck
    steps:

      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: ShellCheck
        run: shellcheck *.sh
