name: CI

on:
  pull_request:
  push:

jobs:

  lint:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Lint install.sh
        run: shellcheck ./install.sh

  run:
    name: Run install.sh
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y zsh
      - name: Run install.sh
        run: ./install.sh
